# server/Dockerfile-dev

# Install node image in container
FROM node

# Install jest and supertest for hot reloading
RUN npm install supertest -g
RUN npm install mocha -g

# Create and set the working directory
RUN mkdir -p /app/server
WORKDIR /app/server

# Copy the dependency files over
COPY package*.json /app/server/

# Install dependencies
RUN npm install

# Copy the server files over
COPY . /app/server/
